### PR TITLE
fixed "Login Unsuccessful"

### PR DESCRIPTION
**Pull request by tkosamja**
The "Login Unsuccessful" box was themed but for some reason it wasn't working (at least in my machine). I think it's fixed now.

### CODE REVIEW

**Comment by DecentM** [comment]
It doesn't seem to change for me. @RaitaroH?

**Comment by tkosamja** [comment]
That's weird. Was the original version working for you?

**Comment by DecentM** [comment]
Nope, but it stayed the same when I removed those lines.

**Comment by tkosamja** [comment]
Can you try now? 
Sorry @RaitaroH I add to commit to see if it works

**Comment by RaitaroH** [comment]
@tkosamja ....
So should I agree with the pull or what?

**Comment by DecentM** [comment]
LGTM

**Comment by tkosamja** [comment]
It's up to you... It works for me but if it doesn't work for other people I don't know

**Comment by RaitaroH** [comment]
It's done.
If you have other stuff to add feel free.

**Comment by tkosamja** [comment]
Nice, I should've thought about cd943df before. Thanks, keep up the good work.

**Comment by RaitaroH** [comment]
There is no reason to do something complicated.

**Pull request merged**
