### PR TITLE
more goodies.

### PR DESCRIPTION
**Pull request by the-j0k3r**
I was testing other browsers and configurations to try find reasons for some issues I have.

The site has quite a lot of font issues because it doesnt account for non standard browser configurations, one such issue is with the ace editor.

Adding more fonts like http://beautifytools.com/stylus-compiler.php does fixes a multitude of problems with ace being poor at handling anything other than monospaced fonts and Windows being crap at font support unlike Linux. see issue https://github.com/OpenUserCSS/openusercss.org/issues/108

Also fixed Chrome and Opera Apple green autofill on inputs at login and other necessary fixes/tweaks.
capture

### CODE REVIEW

**Comment by RaitaroH** [comment]
Btw @the-j0k3r , I have pushed all my stuff to gitlab. I will move there as soon as the whole Micro-shift.

**Comment by the-j0k3r** [comment]
Thats me out then Im not going to join gitlab

**Comment by RaitaroH** [comment]
@the-j0k3r what will you do then?

**Comment by RaitaroH** [comment]
yo @DecentM you moving to gitlab?

**Comment by the-j0k3r** [comment]
Im not a bandwagon kind of guy and am not about to start now. I hate MS's policies too and if they affect GitHub or how I use it, Ill go private or Bitbucket or something else except GitLab who is the poor cousin and l dont like anything about it.

**Comment by RaitaroH** [comment]
I will wait to see what ms will do too. Right now I just pushed my stuff to gitlab.

**Comment by the-j0k3r** [comment]
I just dont want more MS fascism especially on actual great opensource tools(some developed by GitHub that MS has competing products) and collaboration. but Im not jumping from here to go eat someone elses brand of fascism either. Ive alot more behind scenes configuration wise that Gitlab just doesn't cut it. Bitbucket is better in that respect but still not up to snuff.

**Comment by the-j0k3r** [comment]
dammit forgot to add something :(

**Pull request merged**
