### PR TITLE
High priority fixes - post 1.1.0

### PR DESCRIPTION
**Pull request by the-j0k3r**
@RaitaroH 

So... It seems the more I dig the more I find, including one or two mistakes I made previously.

936c998  is somewhat urgent fix, because it prevents using the remove button in theme submission friendly mode. This is my mistake, sorry :(

the rest should be self explanatory, and only leaves one portion Im trying to fix which is to target the card image directly in order to style it. Im having issues with that and may require assistance.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
another fix incoming in a sec

**Comment by the-j0k3r** [comment]
openusercss is like a pinata and I still haven't made the logos compliant with the brand guidelines hahaha.

**Comment by RaitaroH** [comment]
Oh, @the-j0k3r shouldn't `.is-brand-primary` which is the card for an user (on their style page) not be main-color but instead have the main-background instead? I know that by default is blue but damn XD

**Comment by RaitaroH** [comment]
I only want to know if that selector appears someplace else. I will await your answer. I can change it myself but don't want you to complain about having issues with a pr.

**Comment by the-j0k3r** [comment]
As far as I know `.is-brand-primary` is right as is, but it could be it reused in more than one place by other targeted selectors, if you do make any changes do make sure you're targeting the side you want directly and not fix one side and break the other.

Ill have another look, but if you post screenshots of what you mean it would be more helpful.

> but don't want you to complain about having issues with a pr.

IDK what this means.

Im not doing this to warm up, just please dont fix things on one side to break another and do leave notes on the CSS.

**Comment by the-j0k3r** [comment]
OK

this is the default rule

```css
.is-brand-primary {
	background: linear-gradient(130deg,#000fe5,#005fff);
	color: #fff;
	border: none;
	box-shadow: 0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);
	transition: box-shadow .2s ease-in-out;
	will-change: box-shadow;
}
```

this is the modified one

```css
.is-brand-primary {
	background: var(--main-color) !important;
	color: var(--main-text) !important;
}
```

They affect specifically the user card and buttons, I can separate one from the other if you want but styling should be same to follow more or less default to some extent.

See it in action.

is-brand-primary

So you want the card background to be main background... OK lets see how that looks.

**Comment by the-j0k3r** [comment]
So, yes, done.

screenshot-2018-6-13 openusercss

Is this what you're after? (specifically targeted selector)

```css
	.card-content.is-brand-primary
	{
		background: var(--main-background) !important;
		color: var(--main-text) !important;
	}
```
and

```css
	/* user card .card-content.is-brand-primary content hr*/
	.is-8 hr
	{
		background: var(--hover-background) !important;
	}
```


Ill do a PR later, maybe I stumble on something else.

**Pull request merged**
